version: "3"
services:
  web:
    build:
      context: ./web
      args:
        NPROCS: 4
        TIMEZONE: Australia/Melbourne
        FLASK_SECRET_KEY: $FLASK_SECRET_KEY
        WTF_CSRF_SECRET_KEY: $WTF_CSRF_SECRET_KEY
        MAIL_USER: $MAIL_USER
        MAIL_PASSWORD: $MAIL_PASSWORD
        ADMIN_PASSWORD: $ADMIN_PASSWORD
        SOURCE_XNAT_USER: $SOURCE_XNAT_USER
        SOURCE_XNAT_PASSWORD: $SOURCE_XNAT_PASSWORD
        TARGET_XNAT_USER: $TARGET_XNAT_USER
        TARGET_XNAT_PASSWORD: $TARGET_XNAT_PASSWORD
    volumes:
      - ./app:/app
      - ./databases:/databases
      - ./uploads:/uploads
      - ./to-import:/to-import
    expose:
      - 8000
  sync:
    build: 
      context: ./sync
      args:
        TIMEZONE: Australia/Melbourne
        CRON: 0 1 * * *  # Run sync at 1am
    volumes:
      - ./databases:/databases
      - ./uploads:/uploads
      - ./backups:/backups
    environment:
      - "PASSPHRASE=$BACKUP_PASSPHRASE"
    links:
      - web
  nginx:
    build:
      context: ./nginx
      args:
        TIMEZONE: Australia/Melbourne
    ports:
     - 80:80
     - 443:443
    links:
      - web
    volumes:
      - ./certs:/etc/nginx/certs
