version: "3"
services:
  web:
    build:
      context: ./web
      args:
        TIMEZONE: Australia/Melbourne
        SECRET_KEY: $SECRET_KEY
        WTF_CSRF_SECRET_KEY: $WTF_CSRF_SECRET_KEY
        MAIL_PASSWORD: $MAIL_PASSWORD
    volumes:
      - ./app:/app
      - ./databases/app.db:/database.db
      - ./uploads:/uploads
      - ./filemaker-import.csv:/filemaker-import.csv
    expose:
      - 8000
  backup:
    build: 
      context: ./backup
      args:
        TIMEZONE: Australia/Melbourne
    environment:
      SETUP_CRON: "0 3 * * *"
    volumes:
      - ./databases/app.db:/database.db
      - ./uploads:/uploads
      - ./backups:/backups
  nginx:
    build:
      context: ./nginx
      args:
        TIMEZONE: Australia/Melbourne
    ports:
     - 80:80
     - 443:443
    links:
      - web
    volumes:
      - ./certs/cert.crt:/etc/nginx/certs/cert.crt
      - ./certs/key.key:/etc/nginx/certs/key.key
