version: "3"
services:
  web:
    build:
      context: ./web
      args:
        NPROCS: 4
        TIMEZONE: $TIMEZONE
        FLASK_SECRET_KEY: $FLASK_SECRET_KEY
        WTF_CSRF_SECRET_KEY: $WTF_CSRF_SECRET_KEY
        MAIL_PASSWORD: $MAIL_PASSWORD
        SOURCE_XNAT_PASSWORD: $SOURCE_XNAT_PASSWORD
        TARGET_XNAT_PASSWORD: $TARGET_XNAT_PASSWORD
    volumes:
      - ./app:/app
      - ./databases/app.db:/database.db
      - ./uploads:/uploads
      - ./to-import/filemaker-export.csv:/filemaker-export.csv
    expose:
      - 8000
  sync:
    build: 
      context: ./sync
      args:
        TIMEZONE: $TIMEZONE
        CRON: 0 1 * * *  # Run sync at 1am
    volumes:
      - ./databases:/databases
      - ./uploads:/uploads
      - ./backups:/backups
      - ./overwritten:/overwritten
    environment:
      - "PASSPHRASE=$BACKUP_PASSPHRASE"
    links:
      - web
  nginx:
    build:
      context: ./nginx
      args:
        TIMEZONE: $TIMEZONE
    ports:
     - 80:80
     - 443:443
    links:
      - web
    volumes:
      - ./certs/cert.crt:/etc/nginx/certs/cert.crt
      - ./certs/key.key:/etc/nginx/certs/key.key
